name: Deploy Golang Slack Chatbot to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build Binary
        run: go build -o chat-bot main.go

      - name: Configure Secrets
        uses: sethvargo/github-action-secrets@v2
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE }}

      - name: Deploy Chatbot
        uses: netlify/actions/cli@v1
        with:
          args: deploy --prod --message "Deploying my-bot" --dir ./
